language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U pytest

# command to run tests
script:
  - black --check --diff .
  - flake8 --max-line-length=88 .
  - coverage run --source=polls,uplyft manage.py test polls

after_success:
  coveralls